  try{const employee=await ask('ФИО сотрудника');if(!employee)return;const name=await ask('Название товара');if(!name||!name.trim())return;const category=await __v13ChooseCategory();if(!category)return;const unitValue=await __v13Select('Тип учёта',[{value:'ml',label:'Миллилитры (бутылки)'},{value:'g',label:'Граммы (упаковки)'},{value:'pcs',label:'Штуки'}]);if(!unitValue)return;let size=1;if(unitValue!=='pcs'){const raw=await ask(unitValue==='ml'?'Объём одной бутылки, мл':'Вес одной упаковки, г','number',unitValue==='ml'?'500':'1000');if(raw==null)return;size=Math.max(1,n(raw))}const min=await ask(`Минимальный остаток, ${unitValue==='g'?'г':unitValue==='pcs'?'шт.':'мл'}`,'number','0');if(min==null)return;const target=await ask('Целевой остаток','number','0');if(target==null)return;const barcode=await ask('QR / штрихкод (необязательно)')||null;const cost=await ask('Закупочная цена за упаковку, BYN (необязательно)','number','');if(cost==null)return;const catSort=Math.max(-1,...(S.products||[]).map(p=>n(p.category_sort)))+1;await __v13CatalogPost('product_upsert',{old_product_key:null,employee,name:name.trim(),category_name:category,category_sort:catSort,package_size:size,stock_unit:unitValue,minimum_amount:n(min),target_amount:n(target),barcode,default_cost:cost===''?null:Number(String(cost).replace(',','.')),cost_currency:'BYN',variance_recheck_amount:0,active:true});toast('Товар добавлен. Фактический остаток появится через поставку или переучёт.');await snapshot();render()}catch(e){toast(e.message,true)}
}
async function __v13EditProduct(){
  try{const p=await chooseProduct('Какой товар редактировать?');if(!p)return;const employee=await ask('ФИО сотрудника');if(!employee)return;const name=await ask('Название товара','text',p.name);if(name==null||!name.trim())return;const category=await __v13ChooseCategory('Категория товара');if(!category)return;const unitValue=await __v13Select('Тип учёта',[{value:'ml',label:'Миллилитры (бутылки)'},{value:'g',label:'Граммы (упаковки)'},{value:'pcs',label:'Штуки'}]);if(!unitValue)return;let size=unitValue==='pcs'?1:p.package_size;if(unitValue!=='pcs'){const raw=await ask(unitValue==='ml'?'Объём одной бутылки, мл':'Вес одной упаковки, г','number',String(size));if(raw==null)return;size=Math.max(1,n(raw))}const min=await ask('Минимальный остаток','number',String(n(p.minimum_amount)));if(min==null)return;const target=await ask('Целевой остаток','number',String(n(p.target_amount)));if(target==null)return;const barcode=await ask('QR / штрихкод','text',p.barcode||'');if(barcode==null)return;const cost=await ask('Закупочная цена за упаковку, BYN','number',p.default_cost==null?'':String(p.default_cost));if(cost==null)return;const threshold=await ask('Порог обязательного повторного пересчёта','number',String(n(p.variance_recheck_amount)));if(threshold==null)return;await __v13CatalogPost('product_upsert',{old_product_key:keyOf(p),employee,name:name.trim(),category_name:category,category_sort:n(p.category_sort),package_size:size,stock_unit:unitValue,minimum_amount:n(min),target_amount:n(target),barcode:barcode.trim()||null,default_cost:cost===''?null:Number(String(cost).replace(',','.')),cost_currency:p.cost_currency||'BYN',variance_recheck_amount:n(threshold),active:p.active!==false});toast('Карточка товара обновлена');await snapshot();render()}catch(e){toast(e.message,true)}
}
async function __v13RenameCategory(){
  try{const oldName=await __v13ChooseCategory('Какую категорию переименовать?');if(!oldName)return;const newName=await ask('Новое название категории','text',oldName);if(!newName||newName.trim()===oldName)return;const employee=await ask('ФИО сотрудника');if(!employee)return;await __v13CatalogPost('category_rename',{old_name:oldName,new_name:newName.trim(),employee});toast('Категория переименована');await snapshot();render()}catch(e){toast(e.message,true)}
}

// ---------- Suppliers ----------
async function __v13SupplierForm(existing=null){
  try{await api('authorize',{},true);const name=await ask('Название поставщика','text',existing?.name||'');if(!name)return;const contact=await ask('Контактное лицо','text',existing?.contact_person||'')||'';const phone=await ask('Телефон','text',existing?.phone||'')||'';const email=await ask('E-mail','text',existing?.email||'')||'';const notes=await ask('Примечание','text',existing?.notes||'')||'';await api('supplier_upsert',{id:existing?.id||null,name:name.trim(),contact_person:contact||null,phone:phone||null,email:email||null,notes:notes||null},true);toast(existing?'Поставщик обновлён':'Поставщик добавлен');await snapshot();render()}catch(e){toast(e.message,true)}
}
async function __v13LinkSupplier(){
  try{await api('authorize',{},true);const p=await chooseProduct('Товар для поставщика');if(!p)return;const sups=(S.suppliers||[]).filter(x=>x.active!==false).map(x=>({value:x.id,label:x.name,sub:[x.phone,x.email].filter(Boolean).join(' • ')}));if(!sups.length)throw Error('Сначала добавьте поставщика');const sid=await __v13Select('Выберите поставщика',sups);if(!sid)return;const sku=await ask('Артикул у поставщика (необязательно)')||null;const price=await ask('Последняя цена за упаковку, BYN','number','');if(price==null)return;const primary=await confirmBox('Основной поставщик','Сделать этого поставщика основным для товара?');await api('supplier_link',{product_key:keyOf(p),supplier_id:sid,supplier_sku:sku,last_price:price===''?null:Number(String(price).replace(',','.')),currency:'BYN',is_primary:primary},true);toast('Поставщик привязан к товару');await snapshot();render()}catch(e){toast(e.message,true)}
}

// ---------- Locations ----------
async function __v13LocationForm(existing=null){
