  try{await api('authorize',{},true);const name=await ask('Название места хранения','text',existing?.name||'');if(!name)return;const primary=await confirmBox('Основное место',existing?.is_primary?'Оставить это место основным?':'Сделать это место основным?');await api('location_upsert',{id:existing?.id||null,name:name.trim(),is_primary:primary},true);toast(existing?'Место обновлено':'Место добавлено');await snapshot();render()}catch(e){toast(e.message,true)}
}
function __v13LocationDetails(location){
  const rows=(S.location_balances||[]).filter(x=>x.location_id===location.id&&x.initialized).map(x=>{const p=(S.products||[]).find(y=>keyOf(y)===x.product_key);return{p,q:n(x.quantity_base)}}).filter(x=>x.p).sort((a,b)=>String(a.p.category_name).localeCompare(String(b.p.category_name),'ru')||String(a.p.name).localeCompare(String(b.p.name),'ru'));
  openModal(`<h2>${esc(location.name)}</h2><div class="muted">${rows.length} позиций с остатком</div><div class="v13-scroll" style="margin-top:10px">${rows.map(x=>`<div class="card"><div class="name">${esc(x.p.name)}</div><div class="muted">${esc(x.p.category_name)}</div><div class="amount">${esc(parts(x.q,x.p))}</div></div>`).join('')||'<div class="muted">Остатков пока нет.</div>'}</div><button onclick="closeModal()" class="secondary" style="width:100%">Закрыть</button>`);
}

// ---------- Corrections and history filters ----------
async function __v13CorrectOperation(o){
  try{if(String(o.id||'').startsWith('local:'))throw Error('Сначала синхронизируйте эту операцию');await api('authorize',{},true);const employee=await ask('ФИО сотрудника');if(!employee)return;const reason=await ask('Причина корректировки');if(!reason)return;openModal(`<h2>Корректировка</h2><p class="muted">Укажите изменение в базовых единицах со знаком + или −. Например: −500 мл или +2 шт.</p><div class="v13-scroll">${(o.lines||[]).map((l,i)=>`<div class="card"><div class="name">${esc(l.product_name)}</div><div class="muted">${esc(l.category_name)} • ${esc(l.stock_unit)}</div><input class="input v13corr" data-i="${i}" type="number" step="1" value="0" placeholder="Изменение"></div>`).join('')}</div><div class="toolbar"><button id="v13CorrOk">Провести корректировку</button><button id="v13CorrCancel" class="secondary">Отмена</button></div>`);$('#v13CorrCancel').onclick=()=>closeModal();$('#v13CorrOk').onclick=async()=>{try{const lines=[...document.querySelectorAll('.v13corr')].map(x=>({line:o.lines[n(x.dataset.i)],delta:n(x.value)})).filter(x=>x.delta!==0).map(x=>({product_key:x.line.product_key,delta_quantity:x.delta}));if(!lines.length){toast('Введите хотя бы одно изменение',true);return}closeModal();const loc=(S.locations.find(x=>x.is_primary)||S.locations[0])?.id||null;await api('correction',{employee,correction_of:o.id,reason,location_id:loc,lines},true);toast('Корректировка проведена отдельной операцией');await snapshot();setTab('history')}catch(e){toast(e.message,true)}}}catch(e){toast(e.message,true)}
}
const __v13PrevRenderHistory=renderHistory;
const __v13PrevWireHistory=wireHistory;
renderHistory=function(){return `<div class="v13-filterbar noPrint"><input id="v13HistSearch" class="input" placeholder="Поиск по сотруднику, товару, документу" value="${esc(__v13HistoryFilter.query)}"><select id="v13HistType" class="input"><option value="">Все операции</option><option value="delivery" ${__v13HistoryFilter.type==='delivery'?'selected':''}>Поставки</option><option value="stocktake" ${__v13HistoryFilter.type==='stocktake'?'selected':''}>Переучёты</option><option value="writeoff" ${__v13HistoryFilter.type==='writeoff'?'selected':''}>Списания</option><option value="transfer" ${__v13HistoryFilter.type==='transfer'?'selected':''}>Перемещения</option><option value="correction" ${__v13HistoryFilter.type==='correction'?'selected':''}>Корректировки</option></select></div>`+__v13PrevRenderHistory()};
function __v13ApplyHistoryFilters(){const q=__v13HistoryFilter.query.trim().toLowerCase();document.querySelectorAll('.op').forEach(card=>{const o=S.operations[n(card.dataset.i)];if(!o)return;const text=[opName(o.operation_type),o.employee_name,o.document_number,o.comment,...(o.lines||[]).flatMap(l=>[l.product_name,l.category_name])].filter(Boolean).join(' ').toLowerCase();const ok=(!q||text.includes(q))&&(!__v13HistoryFilter.type||o.operation_type===__v13HistoryFilter.type);card.classList.toggle('v13-hidden',!ok)})}
wireHistory=function(){__v13PrevWireHistory();const q=$('#v13HistSearch'),t=$('#v13HistType');if(q)q.oninput=e=>{__v13HistoryFilter.query=e.target.value;__v13ApplyHistoryFilters()};if(t)t.onchange=e=>{__v13HistoryFilter.type=e.target.value;__v13ApplyHistoryFilters()};document.querySelectorAll('.op').forEach(card=>{const o=S.operations[n(card.dataset.i)];if(!o)return;card.dataset.type=o.operation_type;const row=card.querySelector('.row');if(row&&o.operation_type!=='correction'&&!String(o.id||'').startsWith('local:')){const b=document.createElement('button');b.className='secondary noPrint';b.textContent='Исправить';b.onclick=e=>{e.preventDefault();e.stopPropagation();__v13CorrectOperation(o)};row.appendChild(b)}if(row&&o.total_value!=null){const v=document.createElement('span');v.className='pill';v.textContent=__v13FmtValue(o.total_value);row.appendChild(v)}});__v13ApplyHistoryFilters()};

// ---------- Purchases: request statuses ----------
renderBuy=function(){
  const sups=Object.fromEntries((S.suppliers||[]).map(x=>[x.id,x.name])),groups={};(S.purchase_suggestions||[]).forEach(x=>(groups[sups[x.preferred_supplier]||'Поставщик не назначен']??=[]).push(x));
  const suggestedTotal=(S.purchase_suggestions||[]).reduce((sum,x)=>{const packages=Math.ceil(n(x.suggested_quantity)/Math.max(1,n(x.package_size)));return sum+(x.last_price&&x.currency==='BYN'?packages*n(x.last_price):0)},0);
